version: '3.8'

services:
  web:
    build: .
    ports:
      - "443:5000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql+pymysql://root@mysql/tfg_tickets
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: tfg_tickets
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
